name: stoned_fenicsx
channels:
  - conda-forge
dependencies:
  - python=3.13
  - fenics-dolfinx=0.9.0
  - petsc4py=3.23.4
  - mpi4py=4.1.0
  - numpy=2.2.6
  - scipy=1.15.3
  - gmsh=4.13.1
  - meshio=5.3.5
  - numba=0.61.2
  - pytest
  - sphinx=9.1.0
  - myst-parser
  - pip
  - pip:
      - gmsh
      - e